site: Amanda Hill, Author

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  books:
    output: true
    permalink: /books/:slug
  movies:
    output: true
    permalink: /movies/:slug
  music:
    output: true
    permalink: /music/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      featured_image: /images/amanda.jpg
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "books"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "movies"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "music"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num/"
  